# Generated by Django 3.0.5 on 2021-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210410_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
